# config.yml
database:
  host: "localhost"
  username: "admin"
  password: "SuperSecretPassword"  # Hardcoded secret

api:
  base_url: "https://api.example.com"
  api_key: "12345-abcde-67890-fghij"  # Hardcoded API key 

aws:
  access_key_id: "AKIAXXXEXAMPLE"  # Hardcoded AWS Access Key (avoid this)
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"  # Hardcoded AWS Secret Key
