name: cx

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  ast_scan:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Checkmarx scan run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: workshop
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: '' # Specify any additional parameters you need here
